### ISSUE TITLE
Makefile isn't able to update the binary

### ISSUE THREAD

**Issue by cdmistman** [jappeace/brightnessctl#5]
output when running after a git pull

    # make install
    echo installing
    installing
    mkdir -p /usr/local/lib/brightnessctl
    cp -R ./*  /usr/local/lib/brightnessctl/
    ln -s /usr/local/lib/brightnessctl/writebrightness.sh /usr/local/bin/brightness
    ln: failed to create symbolic link '/usr/local/bin/brightness': File exists
    makefile:4: recipe for target 'install' failed
    make: *** [install] Error 1

**Comment by cdmistman** [comment]
I can make a few changes to the makefile (including making the echo statements "silent" so that you only see "installing" instead of "echo installing    installing") if you give me write access :)

**Comment by jappeace** [comment]
Hi donnellycolton,

These changes should solve your problem of not updating: https://github.com/jappeace/brightnessctl/pull/6/files
If you don't like that solution please make an alternative PR. If you do like it then say so and I'll merge it in.

After you've made a couple of PRs I would give you direct write access, but this is to first time I've  heard of you so I'm a bit cautious of that.

**Comment by jappeace** [comment]
Since you remain silent I presume you like the implemented fix.
